on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  CI:
    runs-on: ubuntu-latest

    name: (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: '3.2', spark_version: '1.6.3', java_version: 'openjdk7'}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
