on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  CI:
    runs-on: ubuntu-latest

    name: (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: '3.2', spark_version: '1.6.3', java_version: 'openjdk7'}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
        continue-on-error: true
      - name: Conditionally patch R internals header file
        if: matrix.config.r == '3.2'
        run: |
          chmod +x ./ci/patch_r_internals_header_file.sh
          "./ci/patch_r_internals_header_file.sh"
        shell: bash
      - name: Install dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
